name: macOS Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode (if needed)
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2' # Specify Xcode version here

    - name: Build the project
      run: |
        # Add commands to build your project, e.g.:
        make build
